packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@expo/cli@57.0.22'
  - expo-modules-core@57.0.16
  - expo-modules-jsi@57.0.8
  - expo@57.0.20
  - expo-notifications@57.0.17
